<template>
  <div>
    <div class="flex justify-center">
      <div class="mb-96 text-center">
        <div v-scrollby="titleScrollbyOptions">
          <h1
            :class="['font-extrabold text-primary logo']"
            style="font-family: 'Courgette'"
          >
            Nobel
          </h1>
          <a
            href="#sequencer-section"
            v-smooth-scroll="{
              duration: 1380,
              easingFunction: 'easeInOutQuad',
            }"
            @click="onScrollDownClick"
          >
            <fa
              icon="chevron-down"
              size="4x"
              class="text-primary scale-up-top"
            ></fa>
          </a>
        </div>
      </div>

      <!-- v-scrollby="{
          styleAttributes: [{ prop: 'opacity', factor: 0.01 }],
          changeFunc: onNobelHeaderScroll.bind(this),
        }" -->
    </div>

    <sequencer-section id="sequencer-section"></sequencer-section>
  </div>
</template>

<script>
import SequencerSection from './sections/sequencer-section.vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faChevronDown } from '@fortawesome/free-solid-svg-icons'
library.add(faChevronDown)

export default {
  components: { SequencerSection },
  head() {},
  data() {
    return {
      titleScrollbyOptions: {
        topOutMode: true,
        styleAttributes: [
          { prop: 'opacity', factor: 0.01 },
          // {
          //   prop: 'transform',
          //   value: 'translateY($value%)',
          //   factor: 0.7,
          //   reverse: true,
          // },
        ],
        changeFunc: function (percent) {
          console.log(percent)
        },
        offset: 200,
      },
    }
  },
  methods: {
    onNobelHeaderScroll(percent) {
      console.log('NobelHeaderScrioll', percent)
    },
    onScrollDownClick() {},
  },
}
</script>

<style lang="scss">
@keyframes scale-up-center {
  0% {
    transform: scale(0.5);
  }
  100% {
    transform: scale(1);
  }
}
.logo {
  margin-top: 30vh;
  font-size: 15rem;
}

.scale-up-top {
  animation: scale-up-top 1.3s cubic-bezier(0.455, 0.03, 0.515, 0.955) infinite
    alternate both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-8-17 15:5:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-top
 * ----------------------------------------
 */
@keyframes scale-up-top {
  0% {
    transform: scale(0.5);
    transform-origin: 50% 0%;
  }
  100% {
    transform: scale(1);
    transform-origin: 50% 0%;
  }
}

.tracking-in-contract {
  animation: tracking-in-contract 0.8s cubic-bezier(0.215, 0.61, 0.355, 1) both;
}

@keyframes tracking-in-contract {
  0% {
    letter-spacing: 1em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    letter-spacing: normal;
    opacity: 1;
  }
}
</style>